[package]
org = "ballerinax"
name = "confluent.cregistry"
version = "@toml.version@"
authors = ["Ballerina"]
export=["confluent.cregistry"]
keywords = ["confluent", "schema_registry", "avro", "serdes"]
repository = "https://github.com/ballerina-platform/module-ballerinax-confluent.cregistry"
license = ["Apache-2.0"]
distribution = "2201.11.0-20241218-101200-109f6cc7"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "schema-registry-native"
version = "@toml.version@"
path = "../native/build/libs/confluent.cregistry-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "kafka-schema-registry-client"
version = "@kafka.schema.registry.version@"
path = "./lib/kafka-schema-registry-client-@kafka.schema.registry.version@.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "common-config"
version = "@common.config.version@"
path = "./lib/common-config-@common.config.version@.jar"

[[platform.java21.dependency]]
groupId = "io.confluent"
artifactId = "common-utils"
version = "@common.utils.version@"
path = "./lib/common-utils-@common.utils.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "@kafka.clients.version@"
path = "./lib/kafka-clients-@kafka.clients.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.avro"
artifactId = "avro"
version = "@avro.version@"
path = "./lib/avro-@avro.version@.jar"

[[platform.java21.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "@jackson.version@"
path = "./lib/jackson-core-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "@jackson.version@"
path = "./lib/jackson-annotations-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@jackson.version@"
path = "./lib/jackson-databind-@jackson.version@.jar"
